CREATE TABLE Category (
  id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  category_name STRING NOT NULL
);

CREATE TABLE Product (
  id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  product_name STRING NOT NULL,
  price DECIMAL(10,1) NOT NULL VALIDATE,
  stock INTEGER NOT NULL VARCHAR(10) VALIDATE,
  category_id INTEGER REFERENCES category(id)
);

CREATE TABLE Tag (
  id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  tag_name STRING
);

CREATE TABLE ProductTag (
  id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  product_id INTEGER REFERENCES tag(id)
);
